### ISSUE TITLE
Run it with TES implementation

### ISSUE THREAD

**Issue by vpnu** [Health-Informatics-UoN/hutch-beacon#120]
## Tasks
- [x] Give TES message with inputs to a TES implementation

## Acceptance Criteria
- [x] Given a TES message the beacon-omop-worker should run
- [x] Get the output of the individuals query back
