### ISSUE TITLE
Submit actual TES message to Submission Layer task API

### ISSUE THREAD

**Issue by vpnu** [Health-Informatics-UoN/hutch-beacon#138]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Create a correct TES message that be run by a TES implementation.

### Acceptance Criteria

- [x] Create TES message for executing the `beacon-omop-worker` image
- [x] POST TES message to Submission API

### Tasks

- [x] Create TES message with: 
  - [x] container image 
  - [x] Set image version in config
  - [x] runs individuals commands 
  - [x] env variables for connecting to DB
  - [x] output directory (minio bucket) 
- Submit with TES message if `UseRoCrate` flag is false

### Confirm creation

- [x] This issue is ready
