### ISSUE TITLE
Make Crate Submission Optional

### ISSUE THREAD

**Issue by vpnu** [Health-Informatics-UoN/hutch-beacon#139]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Create FeatureFlag for using RO-Crates for submitting to TRE-FX Sub Layer

### Acceptance Criteria

- [x] RO-Crate creation and submission is optional.
- [x] `UseRoCrate` feature flag exists with default false

### Tasks

- [x] Create `UseRoCrate` Feature Flag
- [x] Add check on crate creation and submission

### Confirm creation

- [x] This issue is ready
