### ISSUE TITLE
CWLtool workflow to run the `beacon-omop-worker` filtering terms

### ISSUE THREAD

**Issue by dcl10** [Health-Informatics-UoN/hutch-beacon#49]
## Description
A CWLtool workflow that will run the script that will query an OMOP database to gather the filtering terms for Beacon. It will save the outputs as a JSON list of filtering term objects.

## Tasks
- [x] Create the workflow file
- [x] Define inputs and outputs
- [x] Test it, if possible
