### ISSUE TITLE
💡 Submit crate to submission layer via the UI

### ISSUE THREAD

**Issue by vpnu** [Health-Informatics-UoN/hutch-beacon#91]
## Tasks
- [x] Create RO-Crate 
   - [x] beacon-omop-worker workflow link
   - [x] defines the inputs to the workflow
- [ ] Submit to submission layer using UI
